# file: roles/build-native/tasks/main.yml
---
- name: set LEIN_ROOT
  shell: export LEIN_ROOT=1

- name: add datastax repository
  shell: echo "deb http://pacotes.linux.locaweb.com.br/cassandra stable main" > /etc/apt/sources.list.d/cassandra.sources.list

- name: install cassandra
  shell: apt-get update; apt-get install -y --allow-unauthenticated dsc20

- name: install consul
  shell: apt-get install -y --allow-unauthenticated consul

- name: install redis
  shell: roles/build-native/files/install-redis.sh

- name: build blackbox
  shell: roles/build-native/files/build-blackbox.sh

- name: build warpdrive
  shell: roles/build-native/files/build-warpdrive.sh
