# file: roles/build-docker/tasks/main.yml
---
- name: make sure debootstrap is installed
  shell: type debootstrap

- name: make sure rinse is installed
  shell: type rinse

- name: make sure docker is running
  service: name=docker state=running

- name: execute stage 0 build
  shell: sudo roles/build-docker/files/stage-0.sh

- name: execute stage 1 build
  shell: roles/build-docker/files/stage-1.sh debian7-amd64.dockerfile

- name: copy leela directory to docker
  shell: docker run -v $(pwd)/roles/build-native/files/leela:/opt/leela_tmp leela/debian7-amd64 cp -r /opt/leela_tmp /opt/leela

- name: commit changes
  shell: docker commit $(docker ps -a -q | awk "NR==1{print $1}") leela/debian7-amd64

- name: add testing repo
  shell: docker run leela/debian7-amd64 sh -c "echo 'deb http://debian.mirror.locaweb.com.br stable main non-free contrib' > /etc/apt/sources.list; apt-get update"

- name: commit changes
  shell: docker commit $(docker ps -a -q | awk "NR==1{print $1}") leela/debian7-amd64

- name: install ansible in docker
  shell: docker run leela/debian7-amd64 apt-get install -y ansible

- name: commit changes
  shell: docker commit $(docker ps -a -q | awk "NR==1{print $1}") leela/debian7-amd64

- name: run build-native
  shell: docker run leela/debian7-amd64 /opt/leela/automation/build.sh -e native

- name: commit changes
  shell: docker commit $(docker ps -a -q | awk "NR==1{print $1}") leela/debian7-amd64
